ProEstimator.Admin/Controllers/TrialSetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Text;
using System.Data;
using System.Data.SqlClient;

using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;

using ProEstimator.Admin.ViewModel;
using ProEstimator.Admin.ViewModel.Logins;

using ProEstimatorData;
using ProEstimatorData.DataModel;
using ProEstimatorData.DataModel.Contracts;

using ProEstimator.Business.Logic;
using ProEstimatorData.DataModel.Admin;
using ProEstimator.Business.Logic.Admin;
using System.Net;
using ProEstimator.Admin.ViewModel.Import;

namespace ProEstimator.Admin.Controllers
{
    public class TrialSetupController : AdminController
    {
        [Route("TrialSetup/List")]
        public ActionResult Index()
        {
            if (!AdminIsValidated())
            {
                Session["AfterLogin"] = "/TrialSetup/List";
                return Redirect("/LogOut");
            }
            else
            {
                TrialSetupVM trialSetupVM = new TrialSetupVM();
                return View(trialSetupVM);
            }
        }

        public JsonResult GetActiveContractTrialForLogin(string loginId)
        {
            TrialSetupVM trialSetupVM = new TrialSetupVM();

            trialSetupVM.SessionSalesRepID = GetSalesRepID();

            int loginID = InputHelper.GetInteger(loginId);

            // Load organization info
            LoginInfo loginInfo = LoginInfo.GetByID(loginID);
            if (loginInfo != null)
            {
                trialSetupVM.IsAccountInPE = true;
                trialSetupVM.IsAccountInWE = false;
                trialSetupVM.LoginID = loginID;
                trialSetupVM.LoginName = loginInfo.LoginName;
                trialSetupVM.Organizationname = loginInfo.Organization;
                trialSetupVM.TrialEndDate = DateTime.Now.AddDays(14).ToShortDateString();

                DateTime? webEstExpiration = ContractManager.GetWebEstExpiration(loginID);
                if (webEstExpiration.HasValue)
                {
                    if (webEstExpiration.Value >= DateTime.Now)
                    {
                        trialSetupVM.TrialEndDate = webEstExpiration.Value.ToShortDateString();
                    }
                }

                SalesRep salesRep = SalesRep.Get(loginInfo.SalesRepID);
                if (salesRep != null)
                {
                    trialSetupVM.SalesRep = salesRep.SalesRepID + " - " + salesRep.FirstName + " " + salesRep.LastName;
                }

                Trial activeTrial = Trial.GetActive(loginID);
                if (activeTrial != null)
                {
                    trialSetupVM.IsActiveTrialExist = true;
                    trialSetupVM.TrialEndDate = activeTrial.EndDate.ToShortDateString();
                }

                Contract activeContract = Contract.GetActive(loginID);
                if (activeContract != null)
                {
                    trialSetupVM.IsActiveContractExist = true;
                }

                // It is when account exists in PE but it need to check in WE also
                if(!trialSetupVM.IsActiveTrialExist && !trialSetupVM.IsActiveContractExist)
                {
                    trialSetupVM = PrepareTrialSetVMForWE(loginID, trialSetupVM);
                }
            }
            else
            {
                trialSetupVM = PrepareTrialSetVMForWE(loginID, trialSetupVM);

                trialSetupVM.IsAccountInPE = false;
                
                trialSetupVM.IsActiveTrialExist = false;
            }

            return Json(trialSetupVM, JsonRequestBehavior.AllowGet);
        }

        private TrialSetupVM PrepareTrialSetVMForWE(int loginID, TrialSetupVM trialSetupVM)
        {
            WebEstAccountInfo webEstAccountInfo = WebEstAccountInfo.GetForFilter(loginID);

            trialSetupVM.IsAccountInWE = false;

            if (webEstAccountInfo != null)
            {
                trialSetupVM.LoginID = webEstAccountInfo.LoginID;
                trialSetupVM.LoginName = webEstAccountInfo.LoginName;
                trialSetupVM.Organizationname = webEstAccountInfo.Organization;
                trialSetupVM.SalesRep = webEstAccountInfo.SalesRepID + " - " + webEstAccountInfo.SalesRepFirstName + " " + webEstAccountInfo.SalesRepLastName;
                trialSetupVM.IsAccountInWE = true;

                trialSetupVM.IsActiveContractExist = true;
                trialSetupVM.TrialEndDate = DateTime.Now.AddDays(14).ToShortDateString();

                DateTime? webEstExpiration = ContractManager.GetWebEstExpiration(loginID);
                if (webEstExpiration.HasValue)
                {
                    if(webEstExpiration.Value >= DateTime.Now)
                    {
                        trialSetupVM.TrialEndDate = webEstExpiration.Value.ToShortDateString();
                    }
                }
            }

            return trialSetupVM;
        }

        public JsonResult ImportWithTrial(string loginId, string trialEndDate)
        {
            int loginID = InputHelper.GetInteger(loginId);

            AdminService adminService = new AdminService();
            var model = adminService.ImportLogin(loginId, 0, trialEndDate);

            Trial trial = Trial.GetActive(loginID);
            if (trial != null)
            {
                trial.HasEMS = true;
                trial.HasFrameData = true;
                trial.Save(ActiveLogin.ID);
            }

            ImportVM importVM = new ImportVM(model);
            importVM.ImpersonateLink = "https://" + System.Configuration.ConfigurationManager.AppSettings["server"] + "?impersonate=" + adminService.Encrypt(loginID);

            return Json(importVM, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ChangeTrial(string loginId, string trialEndDate)
        {
            int loginID = InputHelper.GetInteger(loginId);
            DateTime endDate = InputHelper.GetDateTime(trialEndDate);

            ImportVM importVM = new ImportVM();
            importVM.LoginID = loginID;
            importVM.Message = "";

            Trial trial = Trial.GetActive(loginID);
            if (trial != null)
            {
                trial.EndDate = endDate;
                SaveResult saveResult = trial.Save(ActiveLogin.ID);
                if (!saveResult.Success)
                {
                    importVM.Message = saveResult.ErrorMessage;
                }
                else
                {
                    importVM.Message = "Trial end date changed";
                }
            }

            AdminService adminService = new AdminService();
            importVM.ImpersonateLink = "https://" + System.Configuration.ConfigurationManager.AppSettings["server"] + "?impersonate=" + adminService.Encrypt(loginID);

            return Json(importVM, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CreateTrial(string loginId, string trialEndDate)
        {
            int loginID = InputHelper.GetInteger(loginId);
            AdminService adminService = new AdminService();

            DateTime startDate = DateTime.Now.Date;
            DateTime endDate = InputHelper.GetDateTime(trialEndDate);

            ContractManager.CreateTrial(loginID, startDate, endDate, true, true, false, true, true, true, false, false);

            // Load organization info
            LoginInfo loginInfo = LoginInfo.GetByID(loginID);

            ImportVM importVM = new ImportVM();
            importVM.LoginID = InputHelper.GetInteger(loginId);
            importVM.LoginName = loginInfo.LoginName;
            importVM.LoginImported = true;
            importVM.Message = "Trial records created successfully";

            importVM.ImpersonateLink = "https://" + System.Configuration.ConfigurationManager.AppSettings["server"] + "?impersonate=" + adminService.Encrypt(loginID);

            return Json(importVM, JsonRequestBehavior.AllowGet);
        }
    }
}

ProEstimator.Admin/Views/TrialSetup/Index.cshtml
@model ProEstimator.Admin.ViewModel.Import.TrialSetupVM

@using ProEstimator.Admin.ViewModel.Import;

@{
    ViewBag.Title = "Administration - Trial Setup";
    Layout = "~/Views/Shared/_LayoutPlain.cshtml";
}

<style>
    .input-group-addon {
        min-width: 150px;
        text-align: left;
    }

    .padd-top {
        padding-top: 30px;
        padding-bottom: 30px;
    }
</style>

<script>

    var createTrialFlag = '';
    var importWithTrialFlag = '';
    var changeTrialFlag = '';

    $(document).ready(function () {
        $("#importTrial").hide();
        $("#impersonate").hide();

        // Set up calendar controls
        $(".date-picker").datepicker({
            showOn: "button",
            buttonImage: "/images/calendar.png",
            buttonImageOnly: true,
            buttonText: "Select date"
        });
    });

    function search() {

        createTrialFlag = '';
        importWithTrialFlag = '';
        changeTrialFlag = '';

        $("#impersonate").hide();
        ShowLoadingOverlay();

        $.ajax({
            url: '@Url.Action("GetActiveContractTrialForLogin", "TrialSetup")',
            type: "POST",
            dataType: "json",
            data: {
                loginId: $('#loginId').val()
            },
            success: function (result) {

                HideLoadingOverlay();

                $('#lblLoginText').text(result.LoginName);
                $('#lblOrganizationText').text(result.Organizationname);
                $('#lblSalesRepText').text(result.SalesRep);
                $('#lblMessage').text('');

                if (result.IsAccountInPE) {
                    if (result.IsActiveTrialExist) {
                        changeTrialFlag = true;

                        // Change text of button element
                        $("#btnImportTrial").text("Change Trial Expiration Date");

                        // EndDate
                        var dateChange = new Date(result.TrialEndDate);
                        var rangeEnd = GetDayMonthYear(dateChange);
                        $("#trialEndDate").val(rangeEnd);

                        // display panel
                        $("#importTrial").show();
                        $('#btnImportTrial').prop('disabled', false);
                    }
                    else if (result.IsActiveContractExist && result.IsAccountInWE == false) {
                        $('#lblMessage').text("User is already set up in PE.");
                        $("#importTrial").hide();
                    }
                    else {
                        createTrialFlag = true;

                        // Change text of button element
                        $("#btnImportTrial").text("Create Trial");

                        // EndDate
                        var dateChange = new Date(result.TrialEndDate);
                        var rangeEnd = GetDayMonthYear(dateChange);
                        $("#trialEndDate").val(rangeEnd);

                        // display panel
                        $("#importTrial").show();
                        $('#btnImportTrial').prop('disabled', false);
                    }
                }
                else if (result.IsAccountInWE) {
                    if (result.IsActiveContractExist) {

                        importWithTrialFlag = true;

                        var dateChange = new Date(result.TrialEndDate);
                        var rangeEnd = GetDayMonthYear(dateChange);

                        $("#trialEndDate").val(rangeEnd);
                        $("#importTrial").show();
                        $('#btnImportTrial').prop('disabled', false);
                    }
                    else {

                        $('#lblMessage').text("Invalid WE contract to create.");
                        $("#importTrial").hide();
                    }
                }
                else {
                    $('#lblMessage').text("Invalid loginID.");
                    $("#importTrial").hide();
                }
            },
            error: function (error) {
                HideLoadingOverlay();
                alert('Search yielded no results.');
            }
        });
    }

    function GetDayMonthYear(dateChange) {
        var d = dateChange.getDate();
        var day = (d < 10) ? '0' + d : d;
        var m = dateChange.getMonth() + 1;
        var month = (m < 10) ? '0' + m : m;
        var yy = dateChange.getYear();
        var year = (yy < 1000) ? yy + 1900 : yy;

        var dateRange = month + "/" + day + "/" + year;

        return dateRange;
    }

    // ImportWithTrial
    function ImportWithTrial() {

        var actionMethod = '';

        if (createTrialFlag) {
            $.ajax({
                url: '@Url.Action("CreateTrial", "TrialSetup")',
                type: "POST",
                dataType: "json",
                data: {
                    loginId: $('#loginId').val(), trialEndDate: $('#trialEndDate').val()
                },
                success: function (result) {
                    successImport(result);
                },
                error: function (error) {
                    failure(error);
                }
            });
        }
        else if (changeTrialFlag) {
            $.ajax({
                url: '@Url.Action("ChangeTrial", "TrialSetup")',
                type: "POST",
                dataType: "json",
                data: {
                    loginId: $('#loginId').val(), trialEndDate: $('#trialEndDate').val()
                },
                success: function (result) {
                    successImport(result);
                },
                error: function (error) {
                    failure(error);
                }
            });
        }
        else if (importWithTrialFlag) {
            $.ajax({
                url: '@Url.Action("ImportWithTrial", "TrialSetup")',
                type: "POST",
                dataType: "json",
                data: {
                    loginId: $('#loginId').val(), trialEndDate: $('#trialEndDate').val()
                },
                success: function (result) {
                    successImport(result);
                },
                error: function (error) {
                    failure(error);
                }
            });
        }        
    }

    function successImport(res) {
        if (res.LoginImported) {

            $("#impersonate").show();
            $("#impersonateLink").attr("href", res.ImpersonateLink);
            $('#btnImportTrial').prop('disabled', true);

            //alert(res.Message);
        } else if (res.ErrorMessage) {
            alert(res.ErrorMessage);
        }
        //else if (res.Message)
        //{
        //    alert(res.Message);
        //}

        search();
    }

    function failure(res) {
        alert(res.ErrorMessage);
    }

</script>

<form id="ImportMaint" name="ImportMaint">
    <br />
    <h4>Trial Setup</h4>
    <br />
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                <label class="col-lg-12 control-label" for="loginId">Login ID</label>
                <div class="col-lg-12">
                    <div class="input-group">
                        <input type="text"
                               class="form-control"
                               placeholder="Login ID"
                               aria-describedby="loginId"
                               id="loginId" />
                    </div>
                    <div class="checkbox">
                        <button class="btn btn-default" type="button" onclick="search();">Search</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6" id="importTrial">
            <div class="form-group">
                <label class="col-lg-12 control-label">Trial End Date</label>
                <div class="col-lg-12">
                    <div class="input-group">
                        <input id="trialEndDate" type="text" class="date-picker" />
                    </div>
                    <div class="checkbox">
                        <button class="btn btn-default" type="button" id="btnImportTrial" onclick="ImportWithTrial()">Import With Trial</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group">
                <label class="col-lg-12" id="lblMessage" style="color:green; font:bold"></label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Account Details</h3>
                </div>
                <div class="panel-body">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="col-lg-5 control-label" id="lblLoginId">Login Name:</label>
                                    <label class="col-lg-7 control-label" id="lblLoginText"></label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="col-lg-5 control-label" id="lblOrganizationName">Organization Name:</label>
                                    <label class="col-lg-7 control-label" id="lblOrganizationText"></label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="col-lg-5 control-label" for="lblSalesRep">Sale Rep:</label>
                                    <label class="col-lg-7 control-label" id="lblSalesRepText"></label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row" id="impersonate">
        <div class="col-lg-2">
            @if (ProEstimator.Business.Logic.Admin.SalesRepPermissionManager.HasPermission(Model.SessionSalesRepID, "UserImpersonate"))
            {
                <a id="impersonateLink" target="_blank" class="pull-right"><input type="button" class="btn btn-default" value="Impersonate" /></a>
            }
        </div>
    </div>
</form>