Proestimator/Controllers/EstimateController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Xml.Serialization;

using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;

using Proestimator.Helpers;
using Proestimator.Resources;
using Proestimator.ViewModel;
using ProEstimator.Business.ILogic;
using ProEstimator.Business.Logic;
using ProEstimator.Business.Model;
using ProEstimatorData;
using ProEstimatorData.DataModel;
using ProEstimatorData.DataModel.ProAdvisor;
using ProEstimatorData.Models;
using ProEstimatorData.Models.EditorTemplateModel;
using ProEstimatorData.Models.SubModel;
using ProEstimatorData.DataModel.PDR;
using ProEstimatorData.DataModel.Profiles;

using Contact = ProEstimatorData.DataModel.Contact;
using Exception = System.Exception;
using Report = ProEstimatorData.DataModel.Report;
using VehicleInfoManual = ProEstimatorData.DataModel.VehicleInfoManual;
using Vendor = ProEstimatorData.DataModel.Vendor;
using Ghostscript.NET.Rasterizer;
using ProEstimator.DataRepositories.Vendors;
using ProEstimator.Business.Panels;
using ProEstimator.Business.Panels.LinkRules;
using ProEstimatorData.DataModel.LinkRules;
using ProEstimator.DataRepositories.Parts;
using ProEstimator.Business.PDR;
using ProEstimator.Business.PDR.Model;
using ProEstimator.Business.ProAdvisor;

namespace Proestimator.Controllers
{
    public class EstimateController : SiteController
    {
        CarfaxService carfaxService = new CarfaxService();

        private IEstimateService _estimateService;
        private IVendorRepository _vendorRepository;
        private IPanelService _panelService;
        private ILinkRuleService _linkRuleService;
        private IPartsService _partsService;
        private IPDRAdditionalOperationsService _pdrAdditionalOperationsService;
        private IProAdvisorService _proAdvisorService;
        private IProAdvisorProfileService _proAdvisorProfileService;
        private ICreditCardPaymentService _creditCardPaymentService;

        public EstimateController(
            IEstimateService estimateService
            , IVendorRepository vendorRepository
            , IPanelService panelService
            , ILinkRuleService linkRuleService
            , IPartsService partsService
            , IPDRAdditionalOperationsService pdrAdditionalOperationsService
            , IProAdvisorService proAdvisorService
            , IProAdvisorProfileService proAdvisorProfileService
            , ICreditCardPaymentService creditCardPaymentService
        )
        {
            _estimateService = estimateService ?? throw new ArgumentNullException(nameof(estimateService));
            _vendorRepository = vendorRepository ?? throw new ArgumentNullException(nameof(vendorRepository));
            _panelService = panelService ?? throw new ArgumentNullException(nameof(panelService));
            _linkRuleService = linkRuleService ?? throw new ArgumentNullException(nameof(linkRuleService));
            _partsService = partsService ?? throw new ArgumentNullException(nameof(partsService));
            _pdrAdditionalOperationsService = pdrAdditionalOperationsService ?? throw new ArgumentNullException(nameof(pdrAdditionalOperationsService));
            _proAdvisorService = proAdvisorService ?? throw new ArgumentNullException(nameof(proAdvisorService));
            _proAdvisorProfileService = proAdvisorProfileService ?? throw new ArgumentNullException(nameof(proAdvisorProfileService));
            _creditCardPaymentService = creditCardPaymentService ?? throw new ArgumentNullException(nameof(creditCardPaymentService));
        }

        // Test Git (DevOps) 2
        [HttpGet]
        [Route("{userID}/new-estimate")]
        public async Task<ActionResult> NewEstimate(int userID)
        {
            Estimate newEstimate = _estimateService.CreateNewEstimate(ActiveLogin);

            return Redirect("/" + userID + "/estimate/" + newEstimate.EstimateID + "/customer");
        }

        [HttpGet]
        [Route("{userID}/new-estimate/{customerID}")]
        public ActionResult NewEstimate(int userID, int customerID)
        {
            // Make sure the customer belongs to the login
            Customer customer = ProEstimatorData.DataModel.Customer.Get(customerID);
            if (customer == null || customer.LoginID != ActiveLogin.LoginID)
            {
                return View(@Proestimator.Resources.ProStrings.InvalidCustomer);
            }

            Estimate newEstimate = _estimateService.CreateNewEstimate(ActiveLogin);

            newEstimate.CustomerID = customerID;
            newEstimate.Save(ActiveLogin.ID);

            return Redirect("/" + userID + "/estimate/" + newEstimate.EstimateID + "/customer");
        }

        #region Customer Page

        [HttpGet]
        [Route("{userID}/estimate/{estimateID}/customer")]
        public ActionResult Customer(int userID, int estimateID)
        {
            Estimate.RefreshProcessedLines(estimateID);

            // Make sure the estimate belongs to the login
            Estimate estimate = new Estimate(estimateID);
            if (estimate.CreatedByLoginID != ActiveLogin.LoginID)
            {
                return Redirect("/" + userID + "?estimate=" + estimateID);
            }

            // Update the last view
            estimate.LastView = DateTime.Now;
            estimate.Save(ActiveLogin.ID);
            estimate = new Estimate(estimateID);

            // If there's no profile, redirect to pick one
            if (estimate.CustomerProfileID == 0)
            {
                LoginInfo loginInfo = LoginInfo.GetByID(ActiveLogin.LoginID);

                if (loginInfo.UseDefaultRateProfile == false)
                {
                    return Redirect("/" + userID + "/estimate/" + estimateID + "/select-rate-profile");
                }
                else
                {
                    List<RateProfile> profiles = RateProfile.GetAllForLogin(ActiveLogin.LoginID);
                    if (profiles != null && (profiles.Where(each => each.IsDefault == true).Count() == 1))
                    {
                        RateProfile profile = profiles.Where(each => each.IsDefault == true).FirstOrDefault();
                        ActiveLogin activeLogin = _siteLoginManager.GetActiveLogin(userID, GetComputerKey());
                        estimate.CustomerProfileID = RateProfileManager.CopyProfile(activeLogin.LoginID, profile.ID, estimateID);

                        // Set the Credit Card fee and flag based the values on the rate profile
                        estimate.CreditCardFeePercentage = profile.CreditCardFeePercentage;
                        estimate.ApplyCreditCardFee = profile.ApplyCreditCardFee;
                        estimate.TaxedCreditCardFee = profile.TaxedCreditCardFee;

                        estimate.Save(ActiveLogin.ID);
                        estimate = new Estimate(estimateID);
                    }
                    else
                    {
                        return Redirect("/" + userID + "/estimate/" + estimateID + "/select-rate-profile");
                    }
                }
            }

            // If there is not a selected Estimator, then redirect the user to select one
            if (estimate.EstimatorID == 0)
            {
                List<Estimator> estimators = Estimator.GetByLogin(ActiveLogin.LoginID);

                if (estimators.Count > 0)
                {
                    return Redirect("/" + userID + "/estimate/" + estimateID + "/select-estimator");
                }
            }

            // If Pro Advisor is on, make sure the estimate has a rate profile
            if (ActiveLogin.HasProAdvisorContract && !estimate.EstimateIsImported)
            {
                if (estimate.AddOnProfileID == 0 && estimateID > InputHelper.GetInteger(ConfigurationManager.AppSettings["FirstAdminInfoIDForAddOns"]))
                {
                    // The estimate has no ProAdvisor proile but needs one.
                    if (_proAdvisorProfileService.UseDefaultProfile(ActiveLogin.LoginID))
                    {
                        ProEstimatorData.DataModel.ProAdvisor.ProAdvisorPresetProfile defaultProfile = _proAdvisorProfileService.GetDefaultProfile(ActiveLogin.LoginID);
                        if (defaultProfile != null)
                        {
                            estimate.AddOnProfileID = defaultProfile.ID;
                            estimate.Save(ActiveLogin.ID);
                            estimate = new Estimate(estimateID);
                        }
                        else
                        {
                            return Redirect("/" + userID + "/estimate/" + estimateID + "/select-add-on-profile");
                        }
                    }
                    else
                    {
                        return Redirect("/" + userID + "/estimate/" + estimateID + "/select-add-on-profile");
                    }
                }
            }

            // Everything checks out, load the view model
            CustomerVM model = new CustomerVM();

            model.EstimateCount = Estimate.GetCountForCustomer(ActiveLogin.LoginID, estimate.CustomerID);

            // Fill the list of existing customers
            List<ProEstimatorData.DataModel.Customer> customers = ProEstimatorData.DataModel.Customer.GetForLogin(ActiveLogin.LoginID).Where(o => o.IsDeleted == false).ToList();
            if (customers.Count > 0)
            {
                model.ExistingCustomers.Add(new ExistingCustomerVM() { CustomerID = 0, CustomerName = "--Select Existing Customer--" });

Proestimator/Views/Estimate/AddParts.cshtml
@model Proestimator.ViewModel.AddPartsVM

@{
    ViewBag.Title = Proestimator.Resources.ProStrings.PageTitle_AddParts;
}

<style>
    #content-area
    {
        right: 0;
        bottom: 0;
        width : auto;
    }

    #lgRowPreset {
        margin-top: 0px !important;
    }

    .form-container {
        padding-top: 20px !important;
    }

    #matrix-large-top-header {
        top: 5px !important;
        right: 27px !important;
    }

    #matrix-large-bottom {
        top: 4px !important;
    }

    .me-form-header {
        display: none;
    }
</style>

<script src="~/Scripts/PaintCalculations.js?18"></script>

<script>

    var _supplement = @Model.Supplement;
    var _estimateIsLocked = @Model.EstimateIsLocked.ToString().ToLower();

    function BeforeRedirect() {
        if ($(".matrix-wrapper").is(":visible")) {
            SavePDR(false);
        }
        if ($(".pdr-mobile-details").is(":visible")) {
            $("#detailsPopupSave").click();
        }
    }

    // Load the passed part ID into the details form for editing.
    function EditLineItem(partID) {
        $.getJSON('@Url.Action("EditME", "RateProfile")', { userID: @ViewBag.UserID, estimateID: @Model.EstimateID, lineID: partID, meMode: "Manual" }, function (data) {
            loadDetails(data.detail, false);
        });
    }

    $(document).ready(function () {
        $(".form-container").css("bottom", "0px");
        applyLoading();

        // Set up the draggable split bar
        var bottomElem = $(".resizable-bottom");
        var bottomElemOriginalHeight = bottomElem.height();
        $(".resizable-top").resizable({
            handles: 's',
            resize: function (event, ui) {
                var bottomHeight = bottomElemOriginalHeight - (ui.element.outerHeight() - ui.originalSize.height);

                // Ensure the height of the line preview section is not less than 30px
                var overLimitAmount = bottomHeight - 30;
                if (overLimitAmount < 0) {
                    bottomHeight += overLimitAmount * -1;
                    ui.element.outerHeight(ui.element.outerHeight() + overLimitAmount);
                }

                bottomElem.height(bottomHeight);

                // If the Manual Entry form is showing, we need to manually set the bottom position of the form-container div
                $(".form-container").css("bottom", (bottomHeight) + "px");

                bottomHeightPct = ($(".resizable-bottom").height() / ($(".resizable-bottom").height() + $(".resizable-top").height())) * 100;
            },
            stop: function (event, ui) {
                bottomElemOriginalHeight = bottomElem.height();
            }
        });

        bottomHeightPct = ($(".resizable-bottom").height() / ($(".resizable-bottom").height() + $(".resizable-top").height())) * 100;
        var bottomHeight = $(".resizable-bottom").height();
        $(".form-container").css("bottom", bottomHeight + "px");

        $("#btnPDR").click(function () {
            ShowPDRPopup();
        });

        $(".pdrHeader").hide();

        @if (Model.PDRAutoOpen)
        {
            <text>
            ShowPDRPopup();
            </text>
        }
    });

    $(window).load(function () {
        removeLoading();
    });

    function ShowPDRPopup() {

        $("#formHeaderRegular").fadeOut(300);

        $("#MEDetails").fadeOut(300, function () {
            $("#PDRMatrixContainer").fadeIn(300);
            $("#formHeaderPDR").fadeIn(300);
        });
    }

    function HidePDR()
    {
        $("#PDRMatrixContainer").fadeOut(300);
        $("#formHeaderPDR").fadeOut(300, function () {
            $("#MEDetails").fadeIn(300);
            $("#formHeaderRegular").fadeIn(300);
        });
    }
</script>

<div id="workDesk" class="page-container">

    @using (Html.BeginForm("AddParts", "Estimate", FormMethod.Post, new { @class = "container" }))
    {
        
        @Html.ValidationSummary(false)
        
        <input type="hidden" id="redirectData" name="redirectDataField" />

        <div id="estimateFormHeader">

            <div id="formHeader-back">
                <a class="button nav-btn" data-link-id="Vehicle-Back" href="javascript:SubmitAndRedirect('/@ViewBag.UserID/estimate/@Model.EstimateID/vehicle');">@Proestimator.Resources.ProStrings.VehicleBackButton</a>
            </div>

            <div id="formHeader-center">

                <div id="formHeaderRegular">
                    <input type="button" class="button nav-btn btnAdd do-not-disable" value=@Proestimator.Resources.ProStrings.AddButton />
                    <input type="button" class="button nav-btn btnClear do-not-disable" value="@Proestimator.Resources.ProStrings.ClearForm">

                    @if (Model.HasPDRContract)
                    {
                        if (Model.PDREnabled)
                        {
                            <input type="button" id="btnPDR" class="button nav-btn do-not-disable" style="min-width: 120px;" value="@Proestimator.Resources.ProStrings.PDR">
                        }
                        else
                        {
                            @Html.ActionLink(Proestimator.Resources.ProStrings.PDR, "ProfileSelect", "PDR", new { errorMessage = "PDR" }, new { @class = "button nav-btn", @style = "min-width: 120px;" })
                        }
                    }
                </div>
                
                <div id="formHeaderPDR" style="display: none;">
                    <input type="button" class="button nav-btn do-not-disable" value="Rate Profile" onclick="SubmitAndRedirect('/@ViewBag.UserID/pdr-rates/@(Model.PDRMatrix != null ? Model.PDRMatrix.ProfileID : Model.PDRMatrixMobile.ProfileID)')" />
                    <input type="button" class="button nav-btn do-not-disable" id="btnSubmit" value="@Proestimator.Resources.ProStrings.Save" />
                    <input type="button" class="button nav-btn do-not-disable" id="btnPDRClose" value="@Proestimator.Resources.ProStrings.Close" />
                </div>
                
                @if (Model.EstimateIsLocked)
                {
                    <p class="error-message">@Proestimator.Resources.ProStrings.Estimate_Message_LockedNoEdit</p>
                }
                
                <div class="message-container error-message">
                </div>
            </div>

            <div id="formHeader-next">
                <a class="button nav-btn" data-link-id="Insurance-Next" href="javascript:SubmitAndRedirect('/@ViewBag.UserID/estimate/@Model.EstimateID/insurance');">@Proestimator.Resources.ProStrings.InsurancePageButton </a>
            </div>

        </div>
        
        <div class="graphical-container" style="top: 75px;">
            <div class="resizable resizable-top">
                <div id="MEDetails" style="height: 100%; overflow: auto;">
                    @Html.EditorFor(model => model.ManualEntry.Details)
                </div>

                @* The PDR Matrix form. *@
                @if (Model.HasPDRContract && Model.PDREnabled)
                {
                    <div id="PDRMatrixContainer" style="display: none; height: 100%; overflow: auto;">
                        @if (Model.PDRMatrix != null)
                        {
                            @Html.EditorFor(model => model.PDRMatrix)
                        }

                        @if (Model.PDRMatrixMobile != null)
                        {
                            @Html.EditorFor(model => model.PDRMatrixMobile)
                        }
                    </div>
                }
            </div>

            <div class="resizable resizable-bottom">
                <div class="graphical-footer">
                    <div id="MEList">
                        @Html.EditorFor(model => model.ManualEntry.List)
                    </div>
                </div>
            </div>
        </div>

    }
</div>

Proestimator/Views/Estimate/CopyEstimate.cshtml
@model Proestimator.ViewModel.CopyEstimateVM

@using ProEstimatorData.Models.SubModel
@{

    ViewBag.Title = Proestimator.Resources.ProStrings.PageTitle_CopyEstimate;
}

<div id="workDesk" class="page-container">
    <br />
    @using (Html.BeginForm("CopyEstimate", "Estimate", FormMethod.Post, new { @id = "estimateForm", @class = "container" }))
    {
        <input type="hidden" id="redirectData" name="redirectDataField" />
        @Html.HiddenFor(o => o.UserID)
        @Html.HiddenFor(o => o.LoginID)
        @Html.HiddenFor(o => o.EstimateID)
        
        <div id="container">

            @if (Model.GoodEstimate)
            {
                
                @* The title and header area *@
                <div id="formHeadline" class="container">
                    <h1 id="vehicleInfoHeadline">
                        @Proestimator.Resources.ProStrings.CopyEstimate
                    </h1>
                </div>

                <div class="half-container">

                    <fieldset id="customerFieldSet" style="text-align: left;">

                        <div class="field-wrapper">
                            <label class="inputLabel field-label"></label>
                            <div class="field-control">
                                <h2>@Proestimator.Resources.ProStrings.EstimateNum: @Model.EstimateID </h2>
                                <h3>@Proestimator.Resources.ProStrings.CopyEstimate_Select</h3>
                            </div>
                        </div>

                        <div class="field-wrapper">
                            <label class="inputLabel field-label"></label>
                            <div class="field-control">
                                @Html.CheckBoxFor(o => o.CreateBlankCustomer) @Proestimator.Resources.ProStrings.CopyEstimate_BlankCustomer
                            </div>
                        </div>

                        <div class="field-wrapper">
                            <label class="inputLabel field-label"></label>
                            <div class="field-control">@Html.CheckBoxFor(o => o.CopyInsuranceInformation) @Proestimator.Resources.ProStrings.CopyEstimate_InsuranceInformation</div>
                        </div>

                        <div class="field-wrapper">
                            <label class="inputLabel field-label"></label>
                            <div class="field-control">@Html.CheckBoxFor(o => o.CopyClaimantInformation) @Proestimator.Resources.ProStrings.CopyEstimate_ClaimantInformation</div>
                        </div>

                        <div class="field-wrapper">
                            <label class="inputLabel field-label"></label>
                            <div class="field-control">@Html.CheckBoxFor(o => o.CopyAttachedImages) @Proestimator.Resources.ProStrings.CopyEstimate_Images</div>
                        </div>

                        <div class="field-wrapper">
                            <label class="inputLabel field-label"></label>
                            <div class="field-control">@Html.CheckBoxFor(o => o.CopyLineItems) @Proestimator.Resources.ProStrings.CopyEstimate_LineItems</div>
                        </div>

                        <div class="field-wrapper">
                            <label class="inputLabel field-label"></label>
                            <div class="field-control">@Html.CheckBoxFor(o => o.CopyLatestItemsOnly) @Proestimator.Resources.ProStrings.CopyEstimate_LatestOnly</div>
                        </div>

                        <div class="field-wrapper">
                            <label class="inputLabel field-label">@Proestimator.Resources.ProStrings.CopyEstimate_EditName:</label>
                            <div class="field-control">
                                @Html.TextBoxFor(o => o.NewName, new { autocomplete = "off" })
                            </div>
                        </div>

                        <div class="field-wrapper">
                            <label class="inputLabel field-label"></label>
                            <div class="field-control">
                                <input id="submitButton" class="button nav-btn" type="submit" value="Copy" />
                                <a class="button nav-btn" href="/@ViewBag.UserID">@Proestimator.Resources.ProStrings.Button_Cancel</a>
                            </div>
                        </div>

                    </fieldset>

                </div>
            }
            else
            {
                <p>@Proestimator.Resources.ProStrings.InvalidEstimateNumber</p>
            }

        </div>
           
    }
</div>

Proestimator/Views/Estimate/RideShareCollisionNetworkCreate.cshtml
@{ Layout = null; }@ViewBag.ErrorMessage

Proestimator/Views/Estimate/SelectAddOnProfile.cshtml
@model Proestimator.ViewModel.SelectRateProfileVM

@using Proestimator.ViewModel;
@using Proestimator.ViewModel.Profiles;

@{
    ViewBag.Title = Proestimator.Resources.ProStrings.RateProfile_Select;
}

<script>
    $(document).ready(function () {

        if ('@Model.UseDefaultAddOnProfile' == 'True') {
            $('#chkToggleUseDefaultAddOnProfile').prop('checked', true);
        }
        else {
            $('#chkToggleUseDefaultAddOnProfile').prop('checked', false);
        }

    });

    $(window).load(function () {
        ShowHideDefaultColumn('@Model.UseDefaultAddOnProfile');
    });

    function ShowHideDefaultColumn(useDefaultAddOnProfile) {
        var grid = $("#addon-profile-info-grid").data("kendoGrid");

        var columns = grid.columns;

        jQuery.each(columns, function (index) {

            if (this.title == "Default") {
                console.log(useDefaultAddOnProfile);
                if ('@Model.UseDefaultAddOnProfile' == 'True' || useDefaultAddOnProfile == true) {
                    grid.showColumn(this);
                }
                else {
                    grid.hideColumn(this);
                }
            }
        });
    }

    function GetSearchParameters()
    {
        var result = { userID: @ViewBag.UserID, estimateID: @Model.EstimateID };
        return result
    }

    function SelectProfile(id)
    {
        $("#SelectedProfileID").val(id);

        @if (!Model.ShowAddOnProfiles)
        {
            <text>
            $("#submitButton").click();
            </text>
        }
        else
        {
            <text>
            $("#ProfileContainer").find(".button").show();
            $("#ProfileContainer").find(".selected-row").removeClass("selected-row");

            var selectedButton = $("#ProfileContainer").find(".button[data-id='" + id + "']");
            var parentRow = selectedButton.closest("tr");
            selectedButton.hide();
            parentRow.find(".profile-description").addClass("selected-row");
            </text>
        }
    }

    function SelectAddOnProfile(id)
    {
        $("#SelectedAddOnProfileID").val(id);
        $("#AddOnProfileContainer").find(".button").show();
        $("#AddOnProfileContainer").find(".selected-row").removeClass("selected-row");

        var selectedButton = $("#AddOnProfileContainer").find(".button[data-id='" + id + "']");
        var parentRow = selectedButton.closest("tr");
        selectedButton.hide();
        parentRow.find(".profile-description").addClass("selected-row");
    }

    function rdoDefaultProfileOnChange(isDefaultCheckBox,profileIDValue) {
        $("#addon-profile-info-grid").find(".rdoDefaultProfile").each(function (index, obj) {
            this.checked = false;
        });

        $.getJSON("/ProAdvisorProfile/SetDefaultRateProfile", { userID: @ViewBag.UserID, profileID: profileIDValue }, function (data) {
            isDefaultCheckBox.checked = true;
            ShowUserMessage(data.ErrorMessage, !data.Success, 3000);
        });
    }

    function ToggleUseDefaultAddOnProfile(defaultAddOnProfileCheckbox) {

        $.getJSON("/ProAdvisorProfile/ToggleUseDefaultProfile", { userID: @ViewBag.UserID }, function (data) {
            if (data.Success)
            {
                ShowHideDefaultColumn(defaultAddOnProfileCheckbox.checked);
            }
            else
            {
                ShowUserMessage("@Proestimator.Resources.ProStrings.ContactSupportUseDefaultProfile.", true, 5000);
            }
        });

    }

</script>

<div id="workDesk" class="page-container">

    @using (Html.BeginForm("SelectAddOnProfile", "Estimate", FormMethod.Post, new { @class = "container" }))
    {

        @Html.HiddenFor(o => o.LoginID)
        @Html.HiddenFor(o => o.EstimateID)

        <div id="formHeader">

            @* The title and header area *@
            <div id="formHeadline" class="container">
                <h2>@Proestimator.Resources.ProStrings.Select @Proestimator.Resources.ProStrings.AddOnRateProfile</h2>
                <div class="inlineNote container">
                </div>
            </div>

        </div>

        <div id="add-on-profile-info-grid-container" class="datagrid" style="width:50%;margin-left:25%">
            <div>
                <label class="switch">
                    <input type="checkbox" id="chkToggleUseDefaultAddOnProfile" onchange="ToggleUseDefaultAddOnProfile(this);">
                    <span class="slider round"></span>
                </label>
                <span style="margin-left: 10px;vertical-align: -webkit-baseline-middle;"><b>Toggle Default Profile</b></span>
            </div>
            @(Html.Kendo().Grid<RateProfileInfo>()
                .Name("addon-profile-info-grid")
                    .Columns(columns =>
                    {
                        columns.Bound("").Template(@<text></text>).ClientTemplate("<input type='radio' class='checkbox-isdefault' onchange='rdoDefaultProfileOnChange(this,#= ID#)' # if (IsDefault) { #" + "checked" + "# } # />").Title("Default").Width("5%");
                        columns.Bound(item => item.ID).Title("ID").Hidden();
                        columns.Bound(item => item.Description).Title("Rate Profile Description").Width("77%");
                        columns.Bound("").Template(@<text></text>).ClientTemplate("<a class='button open-button' href='/" + @ViewBag.UserID + "/estimate/" + @Model.EstimateID + "/select-add-on-profile/#= ID#'>Select</a>").Title("").Width("13%");
                    })
                    .Selectable()
                    .DataSource(dataSource => dataSource
                        .Ajax()
                        .ServerOperation(false)
                        .Read(read => read.Action("GetAddOnProfileList", "Estimate").Data("GetSearchParameters"))
                    ))
        </div>
    }
</div>

Proestimator/Views/Estimate/SelectEstimator.cshtml
@model Proestimator.ViewModel.SelectEstimatorVM
@using Proestimator.ViewModel;
@{
    ViewBag.Title = Proestimator.Resources.ProStrings.Estimator_Select;
}
<script>
    function SelectEstimator(id) {
        $("#SelectedEstimatorID").val(id);
        $("#submitButton").click();
    }
</script>
<style>
    .selected-row {
        font-weight: bold;
    }
</style>
<div id="workDesk" class="page-container">
    @using (Html.BeginForm("SelectEstimator", "Estimate", FormMethod.Post, new { @class = "container" }))
    {
        @Html.HiddenFor(o => o.UserID)
        @Html.HiddenFor(o => o.LoginID)
        @Html.HiddenFor(o => o.EstimateID)
        <div id="formHeader">
            @* The title and header area *@
            <div id="formHeadline" class="container">
                <h2>@Proestimator.Resources.ProStrings.Estimator_Select</h2>
                <div class="inlineNote container">
                </div>
            </div>
        </div>
        <div id="lgRow1" class="container">
            <div>
                <table style="margin:  0px auto;width: 400px;" cellpadding="10">
                    @if (Model.Estimators.Count == 0)
                    {
                        <tr>
                            <td width="100" colspan="2">
                                <span>
                                    There are no Estimators set. Go to the
                                    <a href="/@Model.UserID/settings/estimators" class="k-link" style="color: blue;">Settings</a>
                                    page to add an Estimator.
                                </span>
                            </td>
                        </tr>
                    }
                    else
                    {
                        foreach (var item in Model.Estimators)
                        {
                            <tr>
                                <td width="100">
                                    <input type="button" title="Select" value="Select" onclick="location.href='/@Model.UserID/estimate/@Model.EstimateID/select-estimator/@item.ID'" class="button">
                                </td>
                                <td>@item.Description</td>
                            </tr>
                        }
                        <tr>
                            <td width="100" colspan="2">
                                <br /><br />
                                <span>
                                    Default Estimator can be set on the
                                    <a href="/@Model.UserID/settings/estimators" class="k-link" style="color: blue;">Settings</a>
                                    page.
                                </span>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    }
</div>